language: python
matrix:
  include:
  - env: TARGET=py2
  - env: TARGET=py3
  - env: TARGET=mypy
  allow_failures:
  - env: TARGET=mypy
sudo: required
services:
- docker
install:
- true
script:
- docker build . -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: kmbasad
  password:
    secure: WaRWX4UpZnqKZodISUDT17ZJaGIDyvr2qX+Osnhh5WAZZ7jXXMrpYHtAXlVJIZVRRVrgaxM7faD8WLtj/P1XO5OfLy+mJG2NRzDy7qfT+3IaPATINm6QIVKikPuentVok7wVDd8yNtixBego99DAtdUbrR/3sTJ/aTSUUicDHdgxYhqaB7XA8894+FV9oYz5xaKkQw6BOThBxGS0PfadjtaqNI0KKIFUeqYDzveok+EYTWxJMriETOV5zsuMvNWddewCVEhmiTW2Nq5AuaTHwIrvTrI2LePAyTFl0K344uFDTrU/NaSuBr9Sz944wwK10iM31I3ytQm13f9CvqzunXH5ST3t4d+sFjcsLoGbSDE3PQuCA1gnybzxcDQfykgysQJoklaEQs4rcXclEev9O1BtbQ7QFurKEI3/FiYK+K6INTZ1oqHMUgvi88Ehk7tyn9pKFxwO6nmOOI9pzoH2iHw5tsBFBEOl3XfOsBe3U9nvGsr2+7ffnDhBgP51H2ZpwngUhkgKFprs2K6qGJbm36zI3p8KIIz/98hI0ofg6GOjZDLj8O73g0z4V85caVV/5WbMv/QGfFZOBAiZT1p+VDYNspZBmcOtJAo7GVnVkTQXtFWPqXorVPzMl7XoDVSrmM1UUgb+w+/naIijzfiwmcFMe77jbcBw8ojCgDAqwVM=
  true:
    tags: true
    repo: ratt-ru/eidos
